export * from './ClientsScroll/ClientsScroll'
export * from './Departments/DepartmentsSection'
export * from './Feedbacks/FeedbacksSection'
export * from './Hero/HeroSection'
export * from './Monitoring/MonitoringSection'
export * from './Specialists/SpecialistsSection'
export * from './Technology/TechnologySection'
